workflows:
  ios-maui:
    name: iOS MAUI Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        SOLUTION_FILE: "RecordHidden.slnx"   # dùng file .slnx của bạn
        PROJECT_NAME: "RecordHidden"         # tên project MAUI
      xcode: latest
      cocoapods: default
      dotnet: 10.0.100   # phiên bản .NET 10.0 SDK

    scripts:
      - name: Restore NuGet packages
        script: |
          dotnet restore "$SOLUTION_FILE"

      - name: Build MAUI iOS app
        script: |
          dotnet build "$SOLUTION_FILE" \
            -c Debug \
            -f net10.0-ios

    artifacts:
      - **/bin/Debug/net10.0-ios/**/*.app
