name: Build MAUI iOS

on:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4

      # Cache NuGet packages
      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install MAUI workloads
        run: dotnet workload install maui maui-ios

      - name: Restore NuGet packages
        run: dotnet restore RecordHidden.csproj

      - name: Build MAUI iOS app
        run: dotnet build RecordHidden.csproj -c Release -f net8.0-ios -v diag

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: "**/bin/Release/net8.0-ios/**/*.app"